### PR TITLE
Add Diffblue CI

### PR DESCRIPTION
**Pull request by ThomasPerkins1123**

### CODE REVIEW

**Comment by db-ci-telescope** [comment]
<HEADER><br><TESTS><b>Existing Tests Status:</b> Running Tests :hourglass_flowing_sand:<br>

**Comment by db-ci-telescope** [comment]
<HEADER><b><u>Diffblue Cover:</u></b> thomas/addDiffblueCI<br><TESTS><b>Existing Tests Status:</b> Running Tests :hourglass_flowing_sand:<br>

**Comment by db-ci-telescope** [comment]
<HEADER><b><u>Diffblue Cover:</u></b> thomas/addDiffblueCI<br><TESTS><b>Existing Tests Status:</b> Existing Tests Pass :heavy_check_mark:<br>

**Comment by db-ci-telescope** [comment]
<HEADER><b><u>Diffblue Cover:</u></b> thomas/addDiffblueCI<br><TESTS><b>Existing Tests Status:</b> Building project :hourglass_flowing_sand:<br>

**Comment by db-ci-telescope** [comment]
<HEADER><b><u>Diffblue Cover:</u></b> thomas/addDiffblueCI<br><TESTS><b>Existing Tests Status:</b> Building project :hourglass_flowing_sand:<br>

**Comment by db-ci-telescope** [comment]
<HEADER><b><u>Diffblue Cover:</u></b> thomas/addDiffblueCI<br><TESTS><b>Existing Tests Status:</b> Building project :hourglass_flowing_sand:<br>

**Comment by db-ci-telescope** [comment]
<HEADER><b><u>Diffblue Cover:</u></b> thomas/addDiffblueCI<br><TEST-GEN><b>Test Generation Status:</b> Diffblue is analysing your pull request :hourglass_flowing_sand:<br>

**Comment by db-ci-telescope** [comment]
<HEADER><b><u>Diffblue Cover:</u></b> thomas/addDiffblueCI<br><TEST-GEN><b>Test Generation Status:</b> Diffblue is analysing your pull request :hourglass_flowing_sand:<br>

**Comment by db-ci-telescope** [comment]
<HEADER><b><u>Diffblue Cover:</u></b> thomas/addDiffblueCI<br><TESTS><b>Existing Tests Status:</b> Building project :hourglass_flowing_sand:<br>

**Comment by db-ci-telescope** [comment]
<HEADER><b><u>Diffblue Cover:</u></b> thomas/addDiffblueCI<br><TESTS><b>Existing Tests Status:</b> Building project :hourglass_flowing_sand:<br>

**Review by EnricoTrentin — APPROVED** [review]

**Pull request merged**
